//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholarship.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUND_COLL_ATTRB
    {
        public FUND_COLL_ATTRB()
        {
            this.FUNDs = new HashSet<FUND>();
        }
    
        public string FUND_COLL_ATTRB1 { get; set; }
        public string FUND_COLL_DESCR { get; set; }
    
        public virtual ICollection<FUND> FUNDs { get; set; }
    }
}
