//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholarship.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUND
    {
        public FUND()
        {
            this.SCHLRSHPs = new HashSet<SCHLRSHP>();
        }
    
        public string FUND_ACCT { get; set; }
        public string FUND_TITLE { get; set; }
        public string FUND_SHORT_TITLE { get; set; }
        public System.DateTime FUND_UPDT_DATEDB { get; set; }
        public string UPDT_USER_ID { get; set; }
        public string FUND_GRP_ATTRB { get; set; }
        public string FUND_PRPS_ATTRB { get; set; }
        public string FUND_LOC_ATTRB { get; set; }
        public string FUND_TYPE_ATTRB { get; set; }
        public string FUND_RVIEW_ATTRB { get; set; }
        public string FUND_COLL_ATTRB { get; set; }
        public string FUND_DEPT_ATTRB { get; set; }
        public string FUND_BDGT_GRP { get; set; }
        public string FUND_BDGT_UNIT { get; set; }
        public string FUND_OPEN_ATTRB { get; set; }
        public System.DateTime FUND_OPEN_DATEDB { get; set; }
        public string FUND_TRNSF_FUND { get; set; }
        public string FUND_ACCT_ID { get; set; }
        public string DONOR_CNSTT_ID { get; set; }
        public string FUND_CMNT { get; set; }
        public string GIFT_PREM_CD { get; set; }
        public string PRMRY_GOAL_ATTRB { get; set; }
        public string SCNDRY_GOAL_ATTRB { get; set; }
        public string FUND_USER_VARBL1 { get; set; }
        public string FUND_USER_VARBL2 { get; set; }
        public string FUND_USER_VARBL3 { get; set; }
        public string LEVY_CD { get; set; }
        public Nullable<long> AUDIT_TRAN_ID { get; set; }
        public string FUND_DDCTN_IND { get; set; }
        public string FUND_ORG_LVL1 { get; set; }
        public string FUND_ORG_LVL2 { get; set; }
        public string FUND_ORG_LVL3 { get; set; }
        public string FUND_ORG_LVL4 { get; set; }
        public string FUND_ORG_LVL5 { get; set; }
        public string TRNSFR_TO_GL { get; set; }
        public string FUND_DESCR { get; set; }
        public Nullable<int> FUND_USER_VARBL4 { get; set; }
        public string FUND_USER_VARBL5 { get; set; }
        public string FUND_USER_VARBL6 { get; set; }
        public string FUND_USER_VARBL7 { get; set; }
        public string FUND_USER_VARBL8 { get; set; }
        public string FUND_USER_VARBL9 { get; set; }
        public string FUND_USER_VARBL10 { get; set; }
        public string SPCL_PROJ { get; set; }
        public Nullable<decimal> FUND_USER_VARBL11 { get; set; }
        public Nullable<decimal> FUND_USER_VARBL12 { get; set; }
        public Nullable<decimal> FUND_USER_VARBL13 { get; set; }
    
        public virtual FUND_DEPT_ATTRB FUND_DEPT_ATTRB1 { get; set; }
        public virtual FUND_COLL_ATTRB FUND_COLL_ATTRB1 { get; set; }
        public virtual ICollection<SCHLRSHP> SCHLRSHPs { get; set; }
    }
}
