//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholarship.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchEntities : DbContext
    {
        public SchEntities()
            : base("name=SchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FUND> FUNDs { get; set; }
        public DbSet<SCHLRSHP> SCHLRSHPs { get; set; }
        public DbSet<USER_CODE> USER_CODE { get; set; }
        public DbSet<FUND_COLL_ATTRB> FUND_COLL_ATTRB { get; set; }
        public DbSet<FUND_DEPT_ATTRB> FUND_DEPT_ATTRB { get; set; }
        public DbSet<USER_CD> USER_CD { get; set; }
    }
}
