//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholarship.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_CODE
    {
        public int USER_CD_SYS_ID { get; set; }
        public string ID { get; set; }
        public string USER_GRP { get; set; }
        public string USER_CD { get; set; }
        public string STTUS_IND { get; set; }
        public System.DateTime BEG_DATEDB { get; set; }
        public Nullable<System.DateTime> END_DATEDB { get; set; }
        public string UC_USER_VARBL1 { get; set; }
        public string UC_USER_VARBL2 { get; set; }
        public string UC_USER_VARBL3 { get; set; }
        public string UC_USER_VARBL4 { get; set; }
        public string UC_USER_VARBL5 { get; set; }
        public string UC_USER_VARBL7 { get; set; }
        public string UC_USER_VARBL8 { get; set; }
        public string UC_USER_VARBL9 { get; set; }
        public string UC_USER_VARBL10 { get; set; }
        public string UC_USER_VARBL11 { get; set; }
        public string UC_USER_VARBL12 { get; set; }
        public string UC_USER_VARBL13 { get; set; }
        public string UC_USER_VARBL14 { get; set; }
        public string UC_USER_VARBL15 { get; set; }
        public string UC_USER_VARBL6 { get; set; }
        public string UPDT_USER_ID { get; set; }
        public System.DateTime UPDT_DATEDB { get; set; }
        public string NOTE { get; set; }
        public Nullable<long> AUDIT_TRAN_ID { get; set; }
        public Nullable<long> PARENT_AUDIT_TRAN_ID { get; set; }
    }
}
